name: Android Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Gradle Global
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.2 # Aquí GitHub instala Gradle por su cuenta

    - name: Compilar APK con Gradle Global
      # Ya no usamos "./gradlew", usamos "gradle" a secas
      run: gradle assembleDebug
