name: Android Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # Eliminamos el cache temporalmente para evitar el error inicial
        
    - name: Dar permisos al ejecutable Gradle
      run: chmod +x gradlew
      continue-on-error: true # Para que no se detenga si ya tiene permisos

    - name: Compilar APK
      run: ./gradlew assembleDebug
